
internal struct DefinitionsFile: Decodable {
    let colors: [String]?
    let departments: [String]?
    let productAdjective: [String]?
    let productMaterial: [String]?
    let productProduct: [String]?
    let femaleFirstName: [String]?
    let maleFirstName: [String]?
    let lastName: [String]?
    let titleDecriptor: [String]?
    let titleLevel: [String]?
    let titleJob: [String]?
    let companyAdjective: [String]?
    let companyBsAdjective: [String]?
    let companyBsNoun: [String]?
    let companyBsVerb: [String]?
    let companyDescriptor: [String]?
    let companyNoun: [String]?
    let hackerAbbreviation: [String]?
    let hackerAdjective: [String]?
    let hackerIngVerb: [String]?
    let hackerNoun: [String]?
    let hackerVerb: [String]?
    let avatarUri: [String]?
    let videoUris: [String]?
    let buildingNumber: [String]?
    let city: [String]?
    let cityPrefix: [String]?
    let citySuffix: [String]?
    let country: [String]?
    let countryCode: [String]?
    let county: [String]?
    let defaultCountry: [String]?
    let direction: [String]?
    let directionAbbr: [String]?
    let postcode: [String]?
    let secondaryAddress: [String]?
    let state: [String]?
    let stateAbbr: [String]?
    let streetAddress: [String]?
    let streetName: [String]?
    let streetSuffix: [String]?
    let streetPrefix: [String]?
    let timeZone: [String]?
    let name: [String]?
    let maleNamePrefix: [String]?
    let femaleNamePrefix: [String]?
    let maleNameSuffix: [String]?
    let femaleNameSuffix: [String]?
    let lorem: [String]?
    let companySuffix: [String]?
    let months: [String]?
    let monthsAbbreviated: [String]?
    let weekdays: [String]?
    let weekdaysAbbreviated: [String]?
    let phoneNumberFormats: [String]?
    let websites: [String]?
}
