public protocol Definitions {
    var buildingNumber: [String] { get set }
    var city: [String] { get set }
    var cityPrefix: [String] { get set }
    var citySuffix: [String] { get set }
    var country: [String] { get set }
    var countryCode: [String] { get set }
    var county: [String] { get set }
    var colors: [String] { get set }
    var departments: [String] { get set }
    var productAdjective: [String] { get set }
    var productMaterial: [String] { get set }
    var productProduct: [String] { get set }
    var defaultCountry: [String] { get set }
    var direction: [String] { get set }
    var directionAbbr: [String] { get set }
    var postcode: [String] { get set }
    var secondaryAddress: [String] { get set }
    var state: [String] { get set }
    var stateAbbr: [String] { get set }
    var streetAddress: [String] { get set }
    var streetName: [String] { get set }
    var streetSuffix: [String] { get set }
    var streetPrefix: [String] { get set }
    var timeZone: [String] { get set }
    var femaleFirstName: [String] { get set }
    var maleFirstName: [String] { get set }
    var lastName: [String] { get set }
    var name: [String] { get set }
    var maleNamePrefix: [String] { get set }
    var femaleNamePrefix: [String] { get set }
    var maleNameSuffix: [String] { get set }
    var femaleNameSuffix: [String] { get set }
    var titleDecriptor: [String] { get set }
    var titleLevel: [String] { get set }
    var titleJob: [String] { get set }
    var firstName: [String] { get set }
    var lorem: [String] { get set }
    var companyAdjective: [String] { get set }
    var companyBsAdjective: [String] { get set }
    var companyBsNoun: [String] { get set }
    var companyBsVerb: [String] { get set }
    var companyDescriptor: [String] { get set }
    var companyNoun: [String] { get set }
    var companySuffix: [String] { get set }
    var months: [String] { get set }
    var monthsAbbreviated: [String] { get set }
    var weekdays: [String] { get set }
    var weekdaysAbbreviated: [String] { get set }
    var hackerAbbreviation: [String] { get set }
    var hackerAdjective: [String] { get set }
    var hackerIngVerb: [String] { get set }
    var hackerNoun: [String] { get set }
    var hackerVerb: [String] { get set }
    var avatarUri: [String] { get set }
    var videoUris: [String] { get set }
    var phoneNumberFormats: [String] { get set }
}
